# Generated by Django 5.1 on 2024-10-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge_supporter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='accept_reward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reward',
            field=models.TextField(null=True),
        ),
    ]
